title: Resume
author:
  name: Saurav Kumar
  email: ar.sauravkr@gmail.com

description: >
  This page is hosted by [Saurav Kumar](https://github.com/arsauravkr)

remote_theme: jekyll/minima

plugins:
  - jekyll-remote-theme

minima:
  skin: auto
  
social_links:
  - { platform: github, user_url: "https://github.com/arsauravkr" }
  - { platform: linkedin, user_url: "https://www.linkedin.com/in/arsauravkr" }
